// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActivityRoom.proto

#ifndef PROTOBUF_ActivityRoom_2eproto__INCLUDED
#define PROTOBUF_ActivityRoom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "Common.pb.h"
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ActivityRoom_2eproto();
void protobuf_AssignDesc_ActivityRoom_2eproto();
void protobuf_ShutdownFile_ActivityRoom_2eproto();

class ActivityRoom;

// ===================================================================

class ActivityRoom : public ::google::protobuf::MessageLite {
 public:
  ActivityRoom();
  virtual ~ActivityRoom();

  ActivityRoom(const ActivityRoom& from);

  inline ActivityRoom& operator=(const ActivityRoom& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ActivityRoom& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ActivityRoom* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ActivityRoom* other);

  // implements Message ----------------------------------------------

  ActivityRoom* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ActivityRoom& from);
  void MergeFrom(const ActivityRoom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 activityID = 1;
  inline bool has_activityid() const;
  inline void clear_activityid();
  static const int kActivityIDFieldNumber = 1;
  inline ::google::protobuf::uint32 activityid() const;
  inline void set_activityid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:yunquan.ActivityRoom)
 private:
  inline void set_has_activityid();
  inline void clear_has_activityid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 activityid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ActivityRoom_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ActivityRoom_2eproto();
  #endif
  friend void protobuf_AssignDesc_ActivityRoom_2eproto();
  friend void protobuf_ShutdownFile_ActivityRoom_2eproto();

  void InitAsDefaultInstance();
  static ActivityRoom* default_instance_;
};
// ===================================================================


// ===================================================================

// ActivityRoom

// required uint32 activityID = 1;
inline bool ActivityRoom::has_activityid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActivityRoom::set_has_activityid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActivityRoom::clear_has_activityid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActivityRoom::clear_activityid() {
  activityid_ = 0u;
  clear_has_activityid();
}
inline ::google::protobuf::uint32 ActivityRoom::activityid() const {
  // @@protoc_insertion_point(field_get:yunquan.ActivityRoom.activityID)
  return activityid_;
}
inline void ActivityRoom::set_activityid(::google::protobuf::uint32 value) {
  set_has_activityid();
  activityid_ = value;
  // @@protoc_insertion_point(field_set:yunquan.ActivityRoom.activityID)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ActivityRoom_2eproto__INCLUDED
