// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupUserAdd.proto

#ifndef PROTOBUF_GroupUserAdd_2eproto__INCLUDED
#define PROTOBUF_GroupUserAdd_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GroupUserAdd_2eproto();
void protobuf_AssignDesc_GroupUserAdd_2eproto();
void protobuf_ShutdownFile_GroupUserAdd_2eproto();

class GroupUserAdd;

// ===================================================================

class GroupUserAdd : public ::google::protobuf::MessageLite {
 public:
  GroupUserAdd();
  virtual ~GroupUserAdd();

  GroupUserAdd(const GroupUserAdd& from);

  inline GroupUserAdd& operator=(const GroupUserAdd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GroupUserAdd& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GroupUserAdd* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GroupUserAdd* other);

  // implements Message ----------------------------------------------

  GroupUserAdd* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GroupUserAdd& from);
  void MergeFrom(const GroupUserAdd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 uid = 1;
  inline int uid_size() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::int32 uid(int index) const;
  inline void set_uid(int index, ::google::protobuf::int32 value);
  inline void add_uid(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      uid() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_uid();

  // optional string content = 2;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 2;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // optional int64 syncKey = 3;
  inline bool has_synckey() const;
  inline void clear_synckey();
  static const int kSyncKeyFieldNumber = 3;
  inline ::google::protobuf::int64 synckey() const;
  inline void set_synckey(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:yunquan.GroupUserAdd)
 private:
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_synckey();
  inline void clear_has_synckey();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > uid_;
  ::std::string* content_;
  ::google::protobuf::int64 synckey_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GroupUserAdd_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GroupUserAdd_2eproto();
  #endif
  friend void protobuf_AssignDesc_GroupUserAdd_2eproto();
  friend void protobuf_ShutdownFile_GroupUserAdd_2eproto();

  void InitAsDefaultInstance();
  static GroupUserAdd* default_instance_;
};
// ===================================================================


// ===================================================================

// GroupUserAdd

// repeated int32 uid = 1;
inline int GroupUserAdd::uid_size() const {
  return uid_.size();
}
inline void GroupUserAdd::clear_uid() {
  uid_.Clear();
}
inline ::google::protobuf::int32 GroupUserAdd::uid(int index) const {
  // @@protoc_insertion_point(field_get:yunquan.GroupUserAdd.uid)
  return uid_.Get(index);
}
inline void GroupUserAdd::set_uid(int index, ::google::protobuf::int32 value) {
  uid_.Set(index, value);
  // @@protoc_insertion_point(field_set:yunquan.GroupUserAdd.uid)
}
inline void GroupUserAdd::add_uid(::google::protobuf::int32 value) {
  uid_.Add(value);
  // @@protoc_insertion_point(field_add:yunquan.GroupUserAdd.uid)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GroupUserAdd::uid() const {
  // @@protoc_insertion_point(field_list:yunquan.GroupUserAdd.uid)
  return uid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GroupUserAdd::mutable_uid() {
  // @@protoc_insertion_point(field_mutable_list:yunquan.GroupUserAdd.uid)
  return &uid_;
}

// optional string content = 2;
inline bool GroupUserAdd::has_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GroupUserAdd::set_has_content() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GroupUserAdd::clear_has_content() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GroupUserAdd::clear_content() {
  if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& GroupUserAdd::content() const {
  // @@protoc_insertion_point(field_get:yunquan.GroupUserAdd.content)
  return *content_;
}
inline void GroupUserAdd::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  content_->assign(value);
  // @@protoc_insertion_point(field_set:yunquan.GroupUserAdd.content)
}
inline void GroupUserAdd::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  content_->assign(value);
  // @@protoc_insertion_point(field_set_char:yunquan.GroupUserAdd.content)
}
inline void GroupUserAdd::set_content(const char* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yunquan.GroupUserAdd.content)
}
inline ::std::string* GroupUserAdd::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    content_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:yunquan.GroupUserAdd.content)
  return content_;
}
inline ::std::string* GroupUserAdd::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GroupUserAdd::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:yunquan.GroupUserAdd.content)
}

// optional int64 syncKey = 3;
inline bool GroupUserAdd::has_synckey() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GroupUserAdd::set_has_synckey() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GroupUserAdd::clear_has_synckey() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GroupUserAdd::clear_synckey() {
  synckey_ = GOOGLE_LONGLONG(0);
  clear_has_synckey();
}
inline ::google::protobuf::int64 GroupUserAdd::synckey() const {
  // @@protoc_insertion_point(field_get:yunquan.GroupUserAdd.syncKey)
  return synckey_;
}
inline void GroupUserAdd::set_synckey(::google::protobuf::int64 value) {
  set_has_synckey();
  synckey_ = value;
  // @@protoc_insertion_point(field_set:yunquan.GroupUserAdd.syncKey)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GroupUserAdd_2eproto__INCLUDED
