// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupUserListRequest.proto

#ifndef PROTOBUF_GroupUserListRequest_2eproto__INCLUDED
#define PROTOBUF_GroupUserListRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GroupUserListRequest_2eproto();
void protobuf_AssignDesc_GroupUserListRequest_2eproto();
void protobuf_ShutdownFile_GroupUserListRequest_2eproto();

class GroupUserListRequest;

// ===================================================================

class GroupUserListRequest : public ::google::protobuf::MessageLite {
 public:
  GroupUserListRequest();
  virtual ~GroupUserListRequest();

  GroupUserListRequest(const GroupUserListRequest& from);

  inline GroupUserListRequest& operator=(const GroupUserListRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GroupUserListRequest& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GroupUserListRequest* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GroupUserListRequest* other);

  // implements Message ----------------------------------------------

  GroupUserListRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GroupUserListRequest& from);
  void MergeFrom(const GroupUserListRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sessionId = 1;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 1;
  inline ::google::protobuf::int32 sessionid() const;
  inline void set_sessionid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:yunquan.GroupUserListRequest)
 private:
  inline void set_has_sessionid();
  inline void clear_has_sessionid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 sessionid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GroupUserListRequest_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GroupUserListRequest_2eproto();
  #endif
  friend void protobuf_AssignDesc_GroupUserListRequest_2eproto();
  friend void protobuf_ShutdownFile_GroupUserListRequest_2eproto();

  void InitAsDefaultInstance();
  static GroupUserListRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// GroupUserListRequest

// required int32 sessionId = 1;
inline bool GroupUserListRequest::has_sessionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GroupUserListRequest::set_has_sessionid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GroupUserListRequest::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GroupUserListRequest::clear_sessionid() {
  sessionid_ = 0;
  clear_has_sessionid();
}
inline ::google::protobuf::int32 GroupUserListRequest::sessionid() const {
  // @@protoc_insertion_point(field_get:yunquan.GroupUserListRequest.sessionId)
  return sessionid_;
}
inline void GroupUserListRequest::set_sessionid(::google::protobuf::int32 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:yunquan.GroupUserListRequest.sessionId)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GroupUserListRequest_2eproto__INCLUDED
