// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupUserListGet.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GroupUserListGet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

void protobuf_ShutdownFile_GroupUserListGet_2eproto() {
  delete GroupUserListGet::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_GroupUserListGet_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_GroupUserListGet_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  GroupUserListGet::default_instance_ = new GroupUserListGet();
  GroupUserListGet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GroupUserListGet_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_GroupUserListGet_2eproto_once_);
void protobuf_AddDesc_GroupUserListGet_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_GroupUserListGet_2eproto_once_,
                 &protobuf_AddDesc_GroupUserListGet_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GroupUserListGet_2eproto {
  StaticDescriptorInitializer_GroupUserListGet_2eproto() {
    protobuf_AddDesc_GroupUserListGet_2eproto();
  }
} static_descriptor_initializer_GroupUserListGet_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int GroupUserListGet::kGroupsessionIdFieldNumber;
#endif  // !_MSC_VER

GroupUserListGet::GroupUserListGet()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yunquan.GroupUserListGet)
}

void GroupUserListGet::InitAsDefaultInstance() {
}

GroupUserListGet::GroupUserListGet(const GroupUserListGet& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yunquan.GroupUserListGet)
}

void GroupUserListGet::SharedCtor() {
  _cached_size_ = 0;
  groupsessionid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GroupUserListGet::~GroupUserListGet() {
  // @@protoc_insertion_point(destructor:yunquan.GroupUserListGet)
  SharedDtor();
}

void GroupUserListGet::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void GroupUserListGet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GroupUserListGet& GroupUserListGet::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GroupUserListGet_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GroupUserListGet_2eproto();
#endif
  return *default_instance_;
}

GroupUserListGet* GroupUserListGet::default_instance_ = NULL;

GroupUserListGet* GroupUserListGet::New() const {
  return new GroupUserListGet;
}

void GroupUserListGet::Clear() {
  groupsessionid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool GroupUserListGet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:yunquan.GroupUserListGet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 groupsessionId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &groupsessionid_)));
          set_has_groupsessionid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yunquan.GroupUserListGet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yunquan.GroupUserListGet)
  return false;
#undef DO_
}

void GroupUserListGet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yunquan.GroupUserListGet)
  // required int32 groupsessionId = 1;
  if (has_groupsessionid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->groupsessionid(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:yunquan.GroupUserListGet)
}

int GroupUserListGet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 groupsessionId = 1;
    if (has_groupsessionid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->groupsessionid());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GroupUserListGet::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GroupUserListGet*>(&from));
}

void GroupUserListGet::MergeFrom(const GroupUserListGet& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_groupsessionid()) {
      set_groupsessionid(from.groupsessionid());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void GroupUserListGet::CopyFrom(const GroupUserListGet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroupUserListGet::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void GroupUserListGet::Swap(GroupUserListGet* other) {
  if (other != this) {
    std::swap(groupsessionid_, other->groupsessionid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string GroupUserListGet::GetTypeName() const {
  return "yunquan.GroupUserListGet";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)
