// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupUserListGet.proto

#ifndef PROTOBUF_GroupUserListGet_2eproto__INCLUDED
#define PROTOBUF_GroupUserListGet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GroupUserListGet_2eproto();
void protobuf_AssignDesc_GroupUserListGet_2eproto();
void protobuf_ShutdownFile_GroupUserListGet_2eproto();

class GroupUserListGet;

// ===================================================================

class GroupUserListGet : public ::google::protobuf::MessageLite {
 public:
  GroupUserListGet();
  virtual ~GroupUserListGet();

  GroupUserListGet(const GroupUserListGet& from);

  inline GroupUserListGet& operator=(const GroupUserListGet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const GroupUserListGet& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GroupUserListGet* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GroupUserListGet* other);

  // implements Message ----------------------------------------------

  GroupUserListGet* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GroupUserListGet& from);
  void MergeFrom(const GroupUserListGet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 groupsessionId = 1;
  inline bool has_groupsessionid() const;
  inline void clear_groupsessionid();
  static const int kGroupsessionIdFieldNumber = 1;
  inline ::google::protobuf::int32 groupsessionid() const;
  inline void set_groupsessionid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:yunquan.GroupUserListGet)
 private:
  inline void set_has_groupsessionid();
  inline void clear_has_groupsessionid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 groupsessionid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GroupUserListGet_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GroupUserListGet_2eproto();
  #endif
  friend void protobuf_AssignDesc_GroupUserListGet_2eproto();
  friend void protobuf_ShutdownFile_GroupUserListGet_2eproto();

  void InitAsDefaultInstance();
  static GroupUserListGet* default_instance_;
};
// ===================================================================


// ===================================================================

// GroupUserListGet

// required int32 groupsessionId = 1;
inline bool GroupUserListGet::has_groupsessionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GroupUserListGet::set_has_groupsessionid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GroupUserListGet::clear_has_groupsessionid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GroupUserListGet::clear_groupsessionid() {
  groupsessionid_ = 0;
  clear_has_groupsessionid();
}
inline ::google::protobuf::int32 GroupUserListGet::groupsessionid() const {
  // @@protoc_insertion_point(field_get:yunquan.GroupUserListGet.groupsessionId)
  return groupsessionid_;
}
inline void GroupUserListGet::set_groupsessionid(::google::protobuf::int32 value) {
  set_has_groupsessionid();
  groupsessionid_ = value;
  // @@protoc_insertion_point(field_set:yunquan.GroupUserListGet.groupsessionId)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GroupUserListGet_2eproto__INCLUDED
