// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModuleLogin.proto

#ifndef PROTOBUF_ModuleLogin_2eproto__INCLUDED
#define PROTOBUF_ModuleLogin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ModuleLogin_2eproto();
void protobuf_AssignDesc_ModuleLogin_2eproto();
void protobuf_ShutdownFile_ModuleLogin_2eproto();

class ModuleLogin;

// ===================================================================

class ModuleLogin : public ::google::protobuf::MessageLite {
 public:
  ModuleLogin();
  virtual ~ModuleLogin();

  ModuleLogin(const ModuleLogin& from);

  inline ModuleLogin& operator=(const ModuleLogin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ModuleLogin& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ModuleLogin* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ModuleLogin* other);

  // implements Message ----------------------------------------------

  ModuleLogin* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ModuleLogin& from);
  void MergeFrom(const ModuleLogin& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 moduleId = 1;
  inline bool has_moduleid() const;
  inline void clear_moduleid();
  static const int kModuleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 moduleid() const;
  inline void set_moduleid(::google::protobuf::uint32 value);

  // required uint32 moduleType = 2;
  inline bool has_moduletype() const;
  inline void clear_moduletype();
  static const int kModuleTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 moduletype() const;
  inline void set_moduletype(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:yunquan.ModuleLogin)
 private:
  inline void set_has_moduleid();
  inline void clear_has_moduleid();
  inline void set_has_moduletype();
  inline void clear_has_moduletype();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 moduleid_;
  ::google::protobuf::uint32 moduletype_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_ModuleLogin_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_ModuleLogin_2eproto();
  #endif
  friend void protobuf_AssignDesc_ModuleLogin_2eproto();
  friend void protobuf_ShutdownFile_ModuleLogin_2eproto();

  void InitAsDefaultInstance();
  static ModuleLogin* default_instance_;
};
// ===================================================================


// ===================================================================

// ModuleLogin

// required uint32 moduleId = 1;
inline bool ModuleLogin::has_moduleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModuleLogin::set_has_moduleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModuleLogin::clear_has_moduleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModuleLogin::clear_moduleid() {
  moduleid_ = 0u;
  clear_has_moduleid();
}
inline ::google::protobuf::uint32 ModuleLogin::moduleid() const {
  // @@protoc_insertion_point(field_get:yunquan.ModuleLogin.moduleId)
  return moduleid_;
}
inline void ModuleLogin::set_moduleid(::google::protobuf::uint32 value) {
  set_has_moduleid();
  moduleid_ = value;
  // @@protoc_insertion_point(field_set:yunquan.ModuleLogin.moduleId)
}

// required uint32 moduleType = 2;
inline bool ModuleLogin::has_moduletype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModuleLogin::set_has_moduletype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModuleLogin::clear_has_moduletype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModuleLogin::clear_moduletype() {
  moduletype_ = 0u;
  clear_has_moduletype();
}
inline ::google::protobuf::uint32 ModuleLogin::moduletype() const {
  // @@protoc_insertion_point(field_get:yunquan.ModuleLogin.moduleType)
  return moduletype_;
}
inline void ModuleLogin::set_moduletype(::google::protobuf::uint32 value) {
  set_has_moduletype();
  moduletype_ = value;
  // @@protoc_insertion_point(field_set:yunquan.ModuleLogin.moduleType)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ModuleLogin_2eproto__INCLUDED
