// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgNotify.proto

#ifndef PROTOBUF_MsgNotify_2eproto__INCLUDED
#define PROTOBUF_MsgNotify_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "Common.pb.h"
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MsgNotify_2eproto();
void protobuf_AssignDesc_MsgNotify_2eproto();
void protobuf_ShutdownFile_MsgNotify_2eproto();

class MsgNotify;

// ===================================================================

class MsgNotify : public ::google::protobuf::MessageLite {
 public:
  MsgNotify();
  virtual ~MsgNotify();

  MsgNotify(const MsgNotify& from);

  inline MsgNotify& operator=(const MsgNotify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const MsgNotify& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MsgNotify* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MsgNotify* other);

  // implements Message ----------------------------------------------

  MsgNotify* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MsgNotify& from);
  void MergeFrom(const MsgNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .yunquan.E_NOTIF_TYPE NotifyType = 1;
  inline bool has_notifytype() const;
  inline void clear_notifytype();
  static const int kNotifyTypeFieldNumber = 1;
  inline ::yunquan::E_NOTIF_TYPE notifytype() const;
  inline void set_notifytype(::yunquan::E_NOTIF_TYPE value);

  // optional uint32 sessionId = 2;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 2;
  inline ::google::protobuf::uint32 sessionid() const;
  inline void set_sessionid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:yunquan.MsgNotify)
 private:
  inline void set_has_notifytype();
  inline void clear_has_notifytype();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int notifytype_;
  ::google::protobuf::uint32 sessionid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MsgNotify_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MsgNotify_2eproto();
  #endif
  friend void protobuf_AssignDesc_MsgNotify_2eproto();
  friend void protobuf_ShutdownFile_MsgNotify_2eproto();

  void InitAsDefaultInstance();
  static MsgNotify* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgNotify

// required .yunquan.E_NOTIF_TYPE NotifyType = 1;
inline bool MsgNotify::has_notifytype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNotify::set_has_notifytype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNotify::clear_has_notifytype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNotify::clear_notifytype() {
  notifytype_ = 0;
  clear_has_notifytype();
}
inline ::yunquan::E_NOTIF_TYPE MsgNotify::notifytype() const {
  // @@protoc_insertion_point(field_get:yunquan.MsgNotify.NotifyType)
  return static_cast< ::yunquan::E_NOTIF_TYPE >(notifytype_);
}
inline void MsgNotify::set_notifytype(::yunquan::E_NOTIF_TYPE value) {
  assert(::yunquan::E_NOTIF_TYPE_IsValid(value));
  set_has_notifytype();
  notifytype_ = value;
  // @@protoc_insertion_point(field_set:yunquan.MsgNotify.NotifyType)
}

// optional uint32 sessionId = 2;
inline bool MsgNotify::has_sessionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNotify::set_has_sessionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNotify::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNotify::clear_sessionid() {
  sessionid_ = 0u;
  clear_has_sessionid();
}
inline ::google::protobuf::uint32 MsgNotify::sessionid() const {
  // @@protoc_insertion_point(field_get:yunquan.MsgNotify.sessionId)
  return sessionid_;
}
inline void MsgNotify::set_sessionid(::google::protobuf::uint32 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:yunquan.MsgNotify.sessionId)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgNotify_2eproto__INCLUDED
