// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Push.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Push.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

namespace {

const ::google::protobuf::Descriptor* Push_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Push_reflection_ = NULL;
const ::google::protobuf::Descriptor* Push_Payload_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Push_Payload_reflection_ = NULL;
const ::google::protobuf::Descriptor* Push_Payload_ExtendedParameter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Push_Payload_ExtendedParameter_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* EventType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* PushType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Push_2eproto() {
  protobuf_AddDesc_Push_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Push.proto");
  GOOGLE_CHECK(file != NULL);
  Push_descriptor_ = file->message_type(0);
  static const int Push_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, pushtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, uidlist_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, messageexpires_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, messagetype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, payload_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, eventtype_),
  };
  Push_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Push_descriptor_,
      Push::default_instance_,
      Push_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Push));
  Push_Payload_descriptor_ = Push_descriptor_->nested_type(0);
  static const int Push_Payload_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, title_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, sound_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, badge_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, extendedparameter_),
  };
  Push_Payload_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Push_Payload_descriptor_,
      Push_Payload::default_instance_,
      Push_Payload_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Push_Payload));
  Push_Payload_ExtendedParameter_descriptor_ = Push_Payload_descriptor_->nested_type(0);
  static const int Push_Payload_ExtendedParameter_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload_ExtendedParameter, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload_ExtendedParameter, val_),
  };
  Push_Payload_ExtendedParameter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Push_Payload_ExtendedParameter_descriptor_,
      Push_Payload_ExtendedParameter::default_instance_,
      Push_Payload_ExtendedParameter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload_ExtendedParameter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Push_Payload_ExtendedParameter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Push_Payload_ExtendedParameter));
  EventType_descriptor_ = file->enum_type(0);
  PushType_descriptor_ = file->enum_type(1);
  MessageType_descriptor_ = file->enum_type(2);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Push_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Push_descriptor_, &Push::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Push_Payload_descriptor_, &Push_Payload::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Push_Payload_ExtendedParameter_descriptor_, &Push_Payload_ExtendedParameter::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Push_2eproto() {
  delete Push::default_instance_;
  delete Push_reflection_;
  delete Push_Payload::default_instance_;
  delete Push_Payload_reflection_;
  delete Push_Payload_ExtendedParameter::default_instance_;
  delete Push_Payload_ExtendedParameter_reflection_;
}

void protobuf_AddDesc_Push_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nPush.proto\022\007yunquan\"\217\003\n\004Push\022#\n\010pushTy"
    "pe\030\001 \002(\0162\021.yunquan.PushType\022\017\n\007uidList\030\002"
    " \003(\005\022\026\n\016messageExpires\030\004 \001(\003\022)\n\013messageT"
    "ype\030\005 \001(\0162\024.yunquan.MessageType\022&\n\007paylo"
    "ad\030\006 \003(\0132\025.yunquan.Push.Payload\022%\n\tevent"
    "Type\030\007 \002(\0162\022.yunquan.EventType\032\276\001\n\007Paylo"
    "ad\022\r\n\005title\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\r"
    "\n\005sound\030\003 \001(\t\022\r\n\005badge\030\004 \001(\005\022B\n\021extended"
    "Parameter\030\005 \003(\0132\'.yunquan.Push.Payload.E"
    "xtendedParameter\032-\n\021ExtendedParameter\022\013\n"
    "\003key\030\001 \002(\t\022\013\n\003val\030\002 \002(\t*\240\002\n\tEventType\022\017\n"
    "\013CHAT_SINGLE\020\001\022\016\n\nCHAT_GROUP\020\002\022\024\n\020ACTIVI"
    "TY_COMMENT\020\003\022\030\n\024ACTIVITY_SIGN_UP_NEW\020\004\022\034"
    "\n\030ACTIVITY_SIGN_UP_SUCCESS\020\005\022\034\n\030ACTIVITY"
    "_SIGN_UP_FAILURE\020\006\022\025\n\021ACTIVITY_UPCOMING\020"
    "\007\022\037\n\033ACTIVITY_INFORMATION_CHANGE\020\010\022\027\n\023US"
    "ER_RELATION_APPLY\020\t\022\027\n\023USER_RELATION_AGR"
    "EE\020\n\022\034\n\030USER_RELATION_NEW_FRIEND\020\013*0\n\010Pu"
    "shType\022\n\n\006SINGLE\020\001\022\t\n\005MULTI\020\002\022\r\n\tBROADCA"
    "ST\020\003*,\n\013MessageType\022\013\n\007MESSAGE\020\001\022\020\n\014NOTI"
    "FICATION\020\002B2\n#cn.iyunquan.push.connector"
    ".protomsgB\013PushMessage", 862);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Push.proto", &protobuf_RegisterTypes);
  Push::default_instance_ = new Push();
  Push_Payload::default_instance_ = new Push_Payload();
  Push_Payload_ExtendedParameter::default_instance_ = new Push_Payload_ExtendedParameter();
  Push::default_instance_->InitAsDefaultInstance();
  Push_Payload::default_instance_->InitAsDefaultInstance();
  Push_Payload_ExtendedParameter::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Push_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Push_2eproto {
  StaticDescriptorInitializer_Push_2eproto() {
    protobuf_AddDesc_Push_2eproto();
  }
} static_descriptor_initializer_Push_2eproto_;
const ::google::protobuf::EnumDescriptor* EventType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EventType_descriptor_;
}
bool EventType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* PushType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PushType_descriptor_;
}
bool PushType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageType_descriptor_;
}
bool MessageType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int Push_Payload_ExtendedParameter::kKeyFieldNumber;
const int Push_Payload_ExtendedParameter::kValFieldNumber;
#endif  // !_MSC_VER

Push_Payload_ExtendedParameter::Push_Payload_ExtendedParameter()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yunquan.Push.Payload.ExtendedParameter)
}

void Push_Payload_ExtendedParameter::InitAsDefaultInstance() {
}

Push_Payload_ExtendedParameter::Push_Payload_ExtendedParameter(const Push_Payload_ExtendedParameter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yunquan.Push.Payload.ExtendedParameter)
}

void Push_Payload_ExtendedParameter::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  val_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Push_Payload_ExtendedParameter::~Push_Payload_ExtendedParameter() {
  // @@protoc_insertion_point(destructor:yunquan.Push.Payload.ExtendedParameter)
  SharedDtor();
}

void Push_Payload_ExtendedParameter::SharedDtor() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (val_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete val_;
  }
  if (this != default_instance_) {
  }
}

void Push_Payload_ExtendedParameter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Push_Payload_ExtendedParameter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Push_Payload_ExtendedParameter_descriptor_;
}

const Push_Payload_ExtendedParameter& Push_Payload_ExtendedParameter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Push_2eproto();
  return *default_instance_;
}

Push_Payload_ExtendedParameter* Push_Payload_ExtendedParameter::default_instance_ = NULL;

Push_Payload_ExtendedParameter* Push_Payload_ExtendedParameter::New() const {
  return new Push_Payload_ExtendedParameter;
}

void Push_Payload_ExtendedParameter::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        key_->clear();
      }
    }
    if (has_val()) {
      if (val_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        val_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Push_Payload_ExtendedParameter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yunquan.Push.Payload.ExtendedParameter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "key");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_val;
        break;
      }

      // required string val = 2;
      case 2: {
        if (tag == 18) {
         parse_val:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_val()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->val().data(), this->val().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "val");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yunquan.Push.Payload.ExtendedParameter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yunquan.Push.Payload.ExtendedParameter)
  return false;
#undef DO_
}

void Push_Payload_ExtendedParameter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yunquan.Push.Payload.ExtendedParameter)
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // required string val = 2;
  if (has_val()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->val().data(), this->val().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "val");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->val(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:yunquan.Push.Payload.ExtendedParameter)
}

::google::protobuf::uint8* Push_Payload_ExtendedParameter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:yunquan.Push.Payload.ExtendedParameter)
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // required string val = 2;
  if (has_val()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->val().data(), this->val().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "val");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->val(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yunquan.Push.Payload.ExtendedParameter)
  return target;
}

int Push_Payload_ExtendedParameter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }

    // required string val = 2;
    if (has_val()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->val());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Push_Payload_ExtendedParameter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Push_Payload_ExtendedParameter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Push_Payload_ExtendedParameter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Push_Payload_ExtendedParameter::MergeFrom(const Push_Payload_ExtendedParameter& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_val()) {
      set_val(from.val());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Push_Payload_ExtendedParameter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Push_Payload_ExtendedParameter::CopyFrom(const Push_Payload_ExtendedParameter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Push_Payload_ExtendedParameter::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Push_Payload_ExtendedParameter::Swap(Push_Payload_ExtendedParameter* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(val_, other->val_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Push_Payload_ExtendedParameter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Push_Payload_ExtendedParameter_descriptor_;
  metadata.reflection = Push_Payload_ExtendedParameter_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Push_Payload::kTitleFieldNumber;
const int Push_Payload::kDescriptionFieldNumber;
const int Push_Payload::kSoundFieldNumber;
const int Push_Payload::kBadgeFieldNumber;
const int Push_Payload::kExtendedParameterFieldNumber;
#endif  // !_MSC_VER

Push_Payload::Push_Payload()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yunquan.Push.Payload)
}

void Push_Payload::InitAsDefaultInstance() {
}

Push_Payload::Push_Payload(const Push_Payload& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yunquan.Push.Payload)
}

void Push_Payload::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  title_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sound_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  badge_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Push_Payload::~Push_Payload() {
  // @@protoc_insertion_point(destructor:yunquan.Push.Payload)
  SharedDtor();
}

void Push_Payload::SharedDtor() {
  if (title_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete title_;
  }
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (sound_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sound_;
  }
  if (this != default_instance_) {
  }
}

void Push_Payload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Push_Payload::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Push_Payload_descriptor_;
}

const Push_Payload& Push_Payload::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Push_2eproto();
  return *default_instance_;
}

Push_Payload* Push_Payload::default_instance_ = NULL;

Push_Payload* Push_Payload::New() const {
  return new Push_Payload;
}

void Push_Payload::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    if (has_title()) {
      if (title_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        title_->clear();
      }
    }
    if (has_description()) {
      if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        description_->clear();
      }
    }
    if (has_sound()) {
      if (sound_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        sound_->clear();
      }
    }
    badge_ = 0;
  }
  extendedparameter_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Push_Payload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yunquan.Push.Payload)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string title = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_title()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->title().data(), this->title().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "title");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_description;
        break;
      }

      // optional string description = 2;
      case 2: {
        if (tag == 18) {
         parse_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_sound;
        break;
      }

      // optional string sound = 3;
      case 3: {
        if (tag == 26) {
         parse_sound:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sound()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sound().data(), this->sound().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sound");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_badge;
        break;
      }

      // optional int32 badge = 4;
      case 4: {
        if (tag == 32) {
         parse_badge:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &badge_)));
          set_has_badge();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_extendedParameter;
        break;
      }

      // repeated .yunquan.Push.Payload.ExtendedParameter extendedParameter = 5;
      case 5: {
        if (tag == 42) {
         parse_extendedParameter:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_extendedparameter()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_extendedParameter;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yunquan.Push.Payload)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yunquan.Push.Payload)
  return false;
#undef DO_
}

void Push_Payload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yunquan.Push.Payload)
  // optional string title = 1;
  if (has_title()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->title().data(), this->title().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "title");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->title(), output);
  }

  // optional string description = 2;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->description(), output);
  }

  // optional string sound = 3;
  if (has_sound()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sound().data(), this->sound().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sound");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sound(), output);
  }

  // optional int32 badge = 4;
  if (has_badge()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->badge(), output);
  }

  // repeated .yunquan.Push.Payload.ExtendedParameter extendedParameter = 5;
  for (int i = 0; i < this->extendedparameter_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->extendedparameter(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:yunquan.Push.Payload)
}

::google::protobuf::uint8* Push_Payload::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:yunquan.Push.Payload)
  // optional string title = 1;
  if (has_title()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->title().data(), this->title().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "title");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->title(), target);
  }

  // optional string description = 2;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->description(), target);
  }

  // optional string sound = 3;
  if (has_sound()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sound().data(), this->sound().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sound");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sound(), target);
  }

  // optional int32 badge = 4;
  if (has_badge()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->badge(), target);
  }

  // repeated .yunquan.Push.Payload.ExtendedParameter extendedParameter = 5;
  for (int i = 0; i < this->extendedparameter_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->extendedparameter(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yunquan.Push.Payload)
  return target;
}

int Push_Payload::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string title = 1;
    if (has_title()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->title());
    }

    // optional string description = 2;
    if (has_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->description());
    }

    // optional string sound = 3;
    if (has_sound()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sound());
    }

    // optional int32 badge = 4;
    if (has_badge()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->badge());
    }

  }
  // repeated .yunquan.Push.Payload.ExtendedParameter extendedParameter = 5;
  total_size += 1 * this->extendedparameter_size();
  for (int i = 0; i < this->extendedparameter_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->extendedparameter(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Push_Payload::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Push_Payload* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Push_Payload*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Push_Payload::MergeFrom(const Push_Payload& from) {
  GOOGLE_CHECK_NE(&from, this);
  extendedparameter_.MergeFrom(from.extendedparameter_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_title()) {
      set_title(from.title());
    }
    if (from.has_description()) {
      set_description(from.description());
    }
    if (from.has_sound()) {
      set_sound(from.sound());
    }
    if (from.has_badge()) {
      set_badge(from.badge());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Push_Payload::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Push_Payload::CopyFrom(const Push_Payload& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Push_Payload::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->extendedparameter())) return false;
  return true;
}

void Push_Payload::Swap(Push_Payload* other) {
  if (other != this) {
    std::swap(title_, other->title_);
    std::swap(description_, other->description_);
    std::swap(sound_, other->sound_);
    std::swap(badge_, other->badge_);
    extendedparameter_.Swap(&other->extendedparameter_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Push_Payload::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Push_Payload_descriptor_;
  metadata.reflection = Push_Payload_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Push::kPushTypeFieldNumber;
const int Push::kUidListFieldNumber;
const int Push::kMessageExpiresFieldNumber;
const int Push::kMessageTypeFieldNumber;
const int Push::kPayloadFieldNumber;
const int Push::kEventTypeFieldNumber;
#endif  // !_MSC_VER

Push::Push()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yunquan.Push)
}

void Push::InitAsDefaultInstance() {
}

Push::Push(const Push& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yunquan.Push)
}

void Push::SharedCtor() {
  _cached_size_ = 0;
  pushtype_ = 1;
  messageexpires_ = GOOGLE_LONGLONG(0);
  messagetype_ = 1;
  eventtype_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Push::~Push() {
  // @@protoc_insertion_point(destructor:yunquan.Push)
  SharedDtor();
}

void Push::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Push::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Push::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Push_descriptor_;
}

const Push& Push::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Push_2eproto();
  return *default_instance_;
}

Push* Push::default_instance_ = NULL;

Push* Push::New() const {
  return new Push;
}

void Push::Clear() {
  if (_has_bits_[0 / 32] & 45) {
    pushtype_ = 1;
    messageexpires_ = GOOGLE_LONGLONG(0);
    messagetype_ = 1;
    eventtype_ = 1;
  }
  uidlist_.Clear();
  payload_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Push::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yunquan.Push)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .yunquan.PushType pushType = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::yunquan::PushType_IsValid(value)) {
            set_pushtype(static_cast< ::yunquan::PushType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_uidList;
        break;
      }

      // repeated int32 uidList = 2;
      case 2: {
        if (tag == 16) {
         parse_uidList:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_uidlist())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_uidlist())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_uidList;
        if (input->ExpectTag(32)) goto parse_messageExpires;
        break;
      }

      // optional int64 messageExpires = 4;
      case 4: {
        if (tag == 32) {
         parse_messageExpires:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &messageexpires_)));
          set_has_messageexpires();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_messageType;
        break;
      }

      // optional .yunquan.MessageType messageType = 5;
      case 5: {
        if (tag == 40) {
         parse_messageType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::yunquan::MessageType_IsValid(value)) {
            set_messagetype(static_cast< ::yunquan::MessageType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_payload;
        break;
      }

      // repeated .yunquan.Push.Payload payload = 6;
      case 6: {
        if (tag == 50) {
         parse_payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_payload()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_payload;
        if (input->ExpectTag(56)) goto parse_eventType;
        break;
      }

      // required .yunquan.EventType eventType = 7;
      case 7: {
        if (tag == 56) {
         parse_eventType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::yunquan::EventType_IsValid(value)) {
            set_eventtype(static_cast< ::yunquan::EventType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(7, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yunquan.Push)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yunquan.Push)
  return false;
#undef DO_
}

void Push::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yunquan.Push)
  // required .yunquan.PushType pushType = 1;
  if (has_pushtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->pushtype(), output);
  }

  // repeated int32 uidList = 2;
  for (int i = 0; i < this->uidlist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->uidlist(i), output);
  }

  // optional int64 messageExpires = 4;
  if (has_messageexpires()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->messageexpires(), output);
  }

  // optional .yunquan.MessageType messageType = 5;
  if (has_messagetype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->messagetype(), output);
  }

  // repeated .yunquan.Push.Payload payload = 6;
  for (int i = 0; i < this->payload_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->payload(i), output);
  }

  // required .yunquan.EventType eventType = 7;
  if (has_eventtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      7, this->eventtype(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:yunquan.Push)
}

::google::protobuf::uint8* Push::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:yunquan.Push)
  // required .yunquan.PushType pushType = 1;
  if (has_pushtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->pushtype(), target);
  }

  // repeated int32 uidList = 2;
  for (int i = 0; i < this->uidlist_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->uidlist(i), target);
  }

  // optional int64 messageExpires = 4;
  if (has_messageexpires()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->messageexpires(), target);
  }

  // optional .yunquan.MessageType messageType = 5;
  if (has_messagetype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->messagetype(), target);
  }

  // repeated .yunquan.Push.Payload payload = 6;
  for (int i = 0; i < this->payload_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->payload(i), target);
  }

  // required .yunquan.EventType eventType = 7;
  if (has_eventtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      7, this->eventtype(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yunquan.Push)
  return target;
}

int Push::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .yunquan.PushType pushType = 1;
    if (has_pushtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->pushtype());
    }

    // optional int64 messageExpires = 4;
    if (has_messageexpires()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->messageexpires());
    }

    // optional .yunquan.MessageType messageType = 5;
    if (has_messagetype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->messagetype());
    }

    // required .yunquan.EventType eventType = 7;
    if (has_eventtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->eventtype());
    }

  }
  // repeated int32 uidList = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->uidlist_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->uidlist(i));
    }
    total_size += 1 * this->uidlist_size() + data_size;
  }

  // repeated .yunquan.Push.Payload payload = 6;
  total_size += 1 * this->payload_size();
  for (int i = 0; i < this->payload_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->payload(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Push::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Push* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Push*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Push::MergeFrom(const Push& from) {
  GOOGLE_CHECK_NE(&from, this);
  uidlist_.MergeFrom(from.uidlist_);
  payload_.MergeFrom(from.payload_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_pushtype()) {
      set_pushtype(from.pushtype());
    }
    if (from.has_messageexpires()) {
      set_messageexpires(from.messageexpires());
    }
    if (from.has_messagetype()) {
      set_messagetype(from.messagetype());
    }
    if (from.has_eventtype()) {
      set_eventtype(from.eventtype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Push::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Push::CopyFrom(const Push& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Push::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000021) != 0x00000021) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->payload())) return false;
  return true;
}

void Push::Swap(Push* other) {
  if (other != this) {
    std::swap(pushtype_, other->pushtype_);
    uidlist_.Swap(&other->uidlist_);
    std::swap(messageexpires_, other->messageexpires_);
    std::swap(messagetype_, other->messagetype_);
    payload_.Swap(&other->payload_);
    std::swap(eventtype_, other->eventtype_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Push::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Push_descriptor_;
  metadata.reflection = Push_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)
