// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserLoginAck.proto

#ifndef PROTOBUF_UserLoginAck_2eproto__INCLUDED
#define PROTOBUF_UserLoginAck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace yunquan {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserLoginAck_2eproto();
void protobuf_AssignDesc_UserLoginAck_2eproto();
void protobuf_ShutdownFile_UserLoginAck_2eproto();

class UserLoginAck;

// ===================================================================

class UserLoginAck : public ::google::protobuf::MessageLite {
 public:
  UserLoginAck();
  virtual ~UserLoginAck();

  UserLoginAck(const UserLoginAck& from);

  inline UserLoginAck& operator=(const UserLoginAck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const UserLoginAck& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const UserLoginAck* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(UserLoginAck* other);

  // implements Message ----------------------------------------------

  UserLoginAck* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const UserLoginAck& from);
  void MergeFrom(const UserLoginAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sessionId = 1;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 1;
  inline ::google::protobuf::int32 sessionid() const;
  inline void set_sessionid(::google::protobuf::int32 value);

  // required int32 result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional string msg = 3;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 3;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:yunquan.UserLoginAck)
 private:
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_msg();
  inline void clear_has_msg();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 sessionid_;
  ::google::protobuf::int32 result_;
  ::std::string* msg_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_UserLoginAck_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_UserLoginAck_2eproto();
  #endif
  friend void protobuf_AssignDesc_UserLoginAck_2eproto();
  friend void protobuf_ShutdownFile_UserLoginAck_2eproto();

  void InitAsDefaultInstance();
  static UserLoginAck* default_instance_;
};
// ===================================================================


// ===================================================================

// UserLoginAck

// required int32 sessionId = 1;
inline bool UserLoginAck::has_sessionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserLoginAck::set_has_sessionid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserLoginAck::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserLoginAck::clear_sessionid() {
  sessionid_ = 0;
  clear_has_sessionid();
}
inline ::google::protobuf::int32 UserLoginAck::sessionid() const {
  // @@protoc_insertion_point(field_get:yunquan.UserLoginAck.sessionId)
  return sessionid_;
}
inline void UserLoginAck::set_sessionid(::google::protobuf::int32 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:yunquan.UserLoginAck.sessionId)
}

// required int32 result = 2;
inline bool UserLoginAck::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserLoginAck::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserLoginAck::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserLoginAck::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 UserLoginAck::result() const {
  // @@protoc_insertion_point(field_get:yunquan.UserLoginAck.result)
  return result_;
}
inline void UserLoginAck::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:yunquan.UserLoginAck.result)
}

// optional string msg = 3;
inline bool UserLoginAck::has_msg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserLoginAck::set_has_msg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserLoginAck::clear_has_msg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserLoginAck::clear_msg() {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& UserLoginAck::msg() const {
  // @@protoc_insertion_point(field_get:yunquan.UserLoginAck.msg)
  return *msg_;
}
inline void UserLoginAck::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set:yunquan.UserLoginAck.msg)
}
inline void UserLoginAck::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:yunquan.UserLoginAck.msg)
}
inline void UserLoginAck::set_msg(const char* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yunquan.UserLoginAck.msg)
}
inline ::std::string* UserLoginAck::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:yunquan.UserLoginAck.msg)
  return msg_;
}
inline ::std::string* UserLoginAck::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UserLoginAck::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:yunquan.UserLoginAck.msg)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace yunquan

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserLoginAck_2eproto__INCLUDED
